/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package owner;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement; 
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import main.Rupiah;
import main.koneksi;

/**
 *
 * @author LENOVO
 */
public class list_produk extends javax.swing.JDialog {

    /**
     * Creates new form list_produk
     */
    public list_produk(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("List Produk");
        showTabel();
        HeaderColumn();
    }

    private void showData(String kodeProduk) {
        try {
            String query = "SELECT * FROM produk WHERE id_produk = '" + kodeProduk + "'";
            Connection conn = (Connection) koneksi.configDB();
            Statement stat = conn.createStatement();
            ResultSet r = stat.executeQuery(query);

            if (r.next()) {
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            System.out.println(ex.getMessage());
        }
    }
    
    public void showTabel() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Id Produk");
        tbl.addColumn("Nama Produk");
        tbl.addColumn("Harga");
        tbl.addColumn("Stok");

        tbl_list_produk.setModel(tbl);
        try {
            String sql = "SELECT * FROM produk";
            Connection con = (Connection) koneksi.configDB();
            Statement st = con.createStatement();
            ResultSet res = st.executeQuery(sql);
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("id_produk"),
                    res.getString("nama_produk"),
                    res.getString("harga"),
                    res.getString("stok")
                });
                tbl_list_produk.setModel(tbl);
//                HeaderColumn();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "salah" + e);
        }
    }
    
    public void HeaderColumn() {
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();

        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        tbl_list_produk.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
        tbl_list_produk.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);

        ((DefaultTableCellRenderer) tbl_list_produk.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
    }
    
    private void cariData(String key) {
        // mencari data 
        try {
            Object[] judul_kolom = {"Id Produk", "Nama Produk", "Harga", "Stok"};
            DefaultTableModel tabModel = new DefaultTableModel(null, judul_kolom);
            tbl_list_produk.setModel(tabModel);

            java.sql.Connection conn = (java.sql.Connection) koneksi.configDB();
            Statement stt = conn.createStatement();
            tabModel.getDataVector().removeAllElements();
            //query pilih data dari produk
            ResultSet RsProduk = stt.executeQuery("SELECT * FROM produk WHERE id_produk LIKE '%"  + key + "%'");
            while (RsProduk.next()) {
                Object[] data = {
                    //data yang dapat dicari 
                    RsProduk.getString("id_produk"),
                    RsProduk.getString("nama_produk"),
                    RsProduk.getString("harga"),
                    RsProduk.getString("stok"),};
                tabModel.addRow(data);
            }
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
    }
    
    private void load() {
        this.txt_cari_produk.setText("");
        this.showTabel();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_list_produk = new javax.swing.JTable();
        txt_cari_produk = new javax.swing.JTextField();
        btn_batal = new javax.swing.JButton();
        btn_pilih = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_list_produk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_list_produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_list_produkMouseClicked(evt);
            }
        });
        tbl_list_produk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbl_list_produkKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_list_produk);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 690, 270));

        txt_cari_produk.setBackground(new java.awt.Color(0,0,0,0)
        );
        txt_cari_produk.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        txt_cari_produk.setForeground(new java.awt.Color(84, 153, 58));
        txt_cari_produk.setBorder(null);
        txt_cari_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cari_produkActionPerformed(evt);
            }
        });
        txt_cari_produk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cari_produkKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cari_produkKeyTyped(evt);
            }
        });
        getContentPane().add(txt_cari_produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 102, 270, 30));

        btn_batal.setBackground(new java.awt.Color(0,0,0,0));
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        getContentPane().add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 110, 30));

        btn_pilih.setBackground(new java.awt.Color(0,0,0,0)
        );
        btn_pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pop up-produk.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_list_produkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_list_produkMouseClicked
        this.showData(this.tbl_list_produk.getValueAt(this.tbl_list_produk.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tbl_list_produkMouseClicked

    private void tbl_list_produkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_list_produkKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int p = tbl_list_produk.getSelectedRow();

            String id = tbl_list_produk.getValueAt(p, 0).toString();
            String nama = tbl_list_produk.getValueAt(p, 1).toString();
            String harga = tbl_list_produk.getValueAt(p, 2).toString();

            
            tr_jual.txt_id_produk.setText(id);
            tr_jual.lbl_nama.setText(nama);
            tr_jual.lbl_harga.setText(harga);
            
            this.dispose();
                        tr_jual.txt_jumlah.requestFocus();

        }
    }//GEN-LAST:event_tbl_list_produkKeyPressed

    private void txt_cari_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cari_produkActionPerformed
         
    }//GEN-LAST:event_txt_cari_produkActionPerformed

    private void txt_cari_produkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cari_produkKeyReleased
        //cari data yg akan dicari
        String key = txt_cari_produk.getText();
        System.out.println(key);
        if (key != "") {
            cariData(key);
        } else {
            load();
        }
    }//GEN-LAST:event_txt_cari_produkKeyReleased

    private void txt_cari_produkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cari_produkKeyTyped
        if ((txt_cari_produk.getText() + evt.getKeyChar()).length() > 29) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_cari_produkKeyTyped

    private void btn_pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihActionPerformed
        int p = tbl_list_produk.getSelectedRow();

            String id = tbl_list_produk.getValueAt(p, 0).toString();
            String nama = tbl_list_produk.getValueAt(p, 1).toString();
            String harga = tbl_list_produk.getValueAt(p, 2).toString();

            
            tr_jual.txt_id_produk.setText(id);
            tr_jual.lbl_nama.setText(nama);
            tr_jual.lbl_harga.setText(harga);
            
            this.dispose();
            tr_jual.txt_jumlah.requestFocus();
    }//GEN-LAST:event_btn_pilihActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        new tr_jual().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(list_produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(list_produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(list_produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(list_produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                list_produk dialog = new list_produk(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_pilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_list_produk;
    private javax.swing.JTextField txt_cari_produk;
    // End of variables declaration//GEN-END:variables

    void setTextIdProduk(String id_produk) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
