/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package owner;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import main.koneksi;

/**
 *
 * @author LENOVO
 */
public class list_supplier extends javax.swing.JDialog {

    /**
     * Creates new form list_supplier
     */
    public list_supplier(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("List Supplier");
        showTabel();
        HeaderColumn();
    }

    private void showData(String kodeSupplier) {
        try {
            String query = "SELECT * FROM supplier WHERE id_supplier = '" + kodeSupplier + "'";
            Connection conn = (Connection) koneksi.configDB();
            Statement stat = conn.createStatement();
            ResultSet r = stat.executeQuery(query);

            if (r.next()) {
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            System.out.println(ex.getMessage());
        }
    }
    
    public void showTabel() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Id Supplier");
        tbl.addColumn("Nama Supplier");
        tbl.addColumn("Alamat");
        tbl.addColumn("No. Telp");

        tbl_list_supplier.setModel(tbl);
        try {
            String sql = "SELECT * FROM supplier";
            Connection con = (Connection) koneksi.configDB();
            Statement st = con.createStatement();
            ResultSet res = st.executeQuery(sql);
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("id_supplier"),
                    res.getString("nama_supplier"),
                    res.getString("alamat"),
                    res.getString("no_telp")
                });
                tbl_list_supplier.setModel(tbl);
//                HeaderColumn();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "salah" + e);
        }
    }
    
    public void HeaderColumn() {
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();

        ((DefaultTableCellRenderer) tbl_list_supplier.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
    }
    
     private void cariData(String key) {
        // mencari data 
        try {
            Object[] judul_kolom = {"Id Supplier", "Nama Supplier", "Alamat", "No. Telp"};
            DefaultTableModel tabModel = new DefaultTableModel(null, judul_kolom);
            tbl_list_supplier.setModel(tabModel);

            java.sql.Connection conn = (java.sql.Connection) koneksi.configDB();
            Statement stt = conn.createStatement();
            tabModel.getDataVector().removeAllElements();
            //query pilih data dari produk
            ResultSet RsProduk = stt.executeQuery("SELECT * FROM supplier WHERE id_supplier LIKE '%"  + key + "%'");
            while (RsProduk.next()) {
                Object[] data = {
                    //data yang dapat dicari 
                    RsProduk.getString("id_supplier"),
                    RsProduk.getString("nama_supplier"),
                    RsProduk.getString("alamat"),
                    RsProduk.getString("no_telp"),};
                tabModel.addRow(data);
            }
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
    }
     
     private void load() {
        this.txt_cari_supplier.setText("");
        this.showTabel();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_list_supplier = new javax.swing.JTable();
        txt_cari_supplier = new javax.swing.JTextField();
        btn_pilih = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_list_supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_list_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_list_supplierMouseClicked(evt);
            }
        });
        tbl_list_supplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbl_list_supplierKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_list_supplierKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbl_list_supplierKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_list_supplier);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 157, 710, 260));

        txt_cari_supplier.setBackground(new java.awt.Color(0,0,0,0)
        );
        txt_cari_supplier.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        txt_cari_supplier.setForeground(new java.awt.Color(84, 153, 58));
        txt_cari_supplier.setBorder(null);
        txt_cari_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cari_supplierActionPerformed(evt);
            }
        });
        getContentPane().add(txt_cari_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 105, 270, -1));

        btn_pilih.setBackground(new java.awt.Color(0,0,0,0)
        );
        btn_pilih.setBorder(null);
        btn_pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 120, 40));

        btn_batal.setBackground(new java.awt.Color(0,0,0,0)
        );
        btn_batal.setBorder(null);
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        getContentPane().add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pop up-supplier.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_list_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_list_supplierMouseClicked
       this.showData(this.tbl_list_supplier.getValueAt(this.tbl_list_supplier.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tbl_list_supplierMouseClicked

    private void tbl_list_supplierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_list_supplierKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int p = tbl_list_supplier.getSelectedRow();

            String id = tbl_list_supplier.getValueAt(p, 0).toString();
            
            transaksi_beli.txt_id_supplier.setText(id);
           
            this.dispose();
                        transaksi_beli.txt_jenis_brg.requestFocus();

        }
    }//GEN-LAST:event_tbl_list_supplierKeyPressed

    private void tbl_list_supplierKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_list_supplierKeyReleased
        //cari data yg akan dicari
        String key = txt_cari_supplier.getText();
        System.out.println(key);
        if (key != "") {
            cariData(key);
        } else {
            load();
        }
    }//GEN-LAST:event_tbl_list_supplierKeyReleased

    private void tbl_list_supplierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_list_supplierKeyTyped
        if ((txt_cari_supplier.getText() + evt.getKeyChar()).length() > 29) {
            evt.consume();
        }
    }//GEN-LAST:event_tbl_list_supplierKeyTyped

    private void btn_pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihActionPerformed
        int p = tbl_list_supplier.getSelectedRow();

            String id = tbl_list_supplier.getValueAt(p, 0).toString();
            
            transaksi_beli.txt_id_supplier.setText(id);
            
            this.dispose();
            transaksi_beli.txt_jenis_brg.requestFocus();
    }//GEN-LAST:event_btn_pilihActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
         new transaksi_beli().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void txt_cari_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cari_supplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cari_supplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(list_supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(list_supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(list_supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(list_supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                list_supplier dialog = new list_supplier(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_pilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_list_supplier;
    private javax.swing.JTextField txt_cari_supplier;
    // End of variables declaration//GEN-END:variables
}
